// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp-1p8jEF2hMq1iU29ZiRCjuFl8bXxeZo',
    appId: '1:57644595957:web:a1db9c523ca7095d0ee3bc',
    messagingSenderId: '57644595957',
    projectId: 'firechat-e9ae6',
    authDomain: 'firechat-e9ae6.firebaseapp.com',
    storageBucket: 'firechat-e9ae6.appspot.com',
    measurementId: 'G-W59M3H2MD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkxqmVPeutdWFrbSfedcpSqg11RMi3JIg',
    appId: '1:57644595957:android:09adc2a3b9593b660ee3bc',
    messagingSenderId: '57644595957',
    projectId: 'firechat-e9ae6',
    storageBucket: 'firechat-e9ae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGF_vqMa1oT-fAhyDVeXmcQteZ_18J-Fc',
    appId: '1:57644595957:ios:9fee49e596ef83b60ee3bc',
    messagingSenderId: '57644595957',
    projectId: 'firechat-e9ae6',
    storageBucket: 'firechat-e9ae6.appspot.com',
    iosBundleId: 'com.example.firechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGF_vqMa1oT-fAhyDVeXmcQteZ_18J-Fc',
    appId: '1:57644595957:ios:b8e55525767f95900ee3bc',
    messagingSenderId: '57644595957',
    projectId: 'firechat-e9ae6',
    storageBucket: 'firechat-e9ae6.appspot.com',
    iosBundleId: 'com.example.firechat.RunnerTests',
  );
}
